EBandPlannerROS:
  differential_drive: false
  max_acceleration: 1.5 #2.5 --> robot falls over in Gazebo
  max_vel_lin: 0.5
  max_vel_th: 1.0
  min_vel_lin: 0.0
  min_vel_th: 0.0
  xy_goal_tolerance: 0.5 #0.02
  yaw_goal_tolerance: 0.2 #0.01
